upstream pn_frontend_main {
  server frontend_main:80;
}
upstream pn_frontend_admission {
  server frontend_admission:80;
}
upstream pn_frontend_admin {
  server frontend_admin:80;
}

upstream pn_auth_api {
  server auth:3001;
}
upstream pn_student_api {
  server student:3002;
}
upstream pn_notification_api {
  server notification:3003;
}

server {
  listen 80;

  client_max_body_size 15m;

  # Health check
  location = /healthz {
    return 200 "ok";
    add_header Content-Type text/plain;
  }

  # --- APIs (gateway) ---
  location /api/auth/ {
    proxy_pass http://pn_auth_api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /api/students/ {
    proxy_pass http://pn_student_api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /api/notifications/ {
    proxy_pass http://pn_notification_api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # --- Micro frontends ---
  location /admission/ {
    proxy_pass http://pn_frontend_admission;
    proxy_set_header Host $host;
  }

  location /admin/ {
    proxy_pass http://pn_frontend_admin;
    proxy_set_header Host $host;
  }

  location / {
    proxy_pass http://pn_frontend_main/;
    proxy_set_header Host $host;
  }
}

